name: mmCustomSkills26
main: com.gmail.berndivader.mmcustomskills26.Main
version: 1.235d
softdepend: [RPGItems, MobArena, HolographicDisplays, WorldGuard, Factions, MassiveCore, Helper]
depend: [MythicMobs]
