name: mmCustomSkills26
main: com.gmail.berndivader.mmcustomskills26.Main
version: 1.182dev
softdepend: [RPGItems, MobArena, HolographicDisplays, WorldGuard, Factions, MassiveCore]
depend: [MythicMobs]
