name: MythicMobsExtension
main: com.gmail.berndivader.mythicmobsext.Main
version: 1.238i
softdepend: [RPGItems, MobArena, HolographicDisplays, WorldGuard, Factions, MassiveCore, Helper]
depend: [MythicMobs]
