name: MythicMobsExtension
main: com.gmail.berndivader.mythicmobsext.Main
version: ${version}
softdepend: [RPGItems, MobArena, HolographicDisplays, WorldGuard, Factions, MassiveCore, Quests, NoCheatPlus]
depend: [MythicMobs]
