name: MythicMobsExtension
main: main.java.com.gmail.berndivader.mythicmobsext.Main
version: 1.239
softdepend: [RPGItems, MobArena, HolographicDisplays, WorldGuard, Factions, MassiveCore, Helper]
depend: [MythicMobs]
